### ISSUE TITLE
Module not found "https://deno.land/x/drash@v2.8.0/mod.ts"bug: 

### ISSUE THREAD

**Issue by sysmat** [drashland/drash#696]
## Summary

A clear and concise summary of the bug.

## Steps To Reproduce The Bug

1. `import * as Drash from "https://deno.land/x/drash@v2.8.0/mod.ts";`
2. error:  `Module not found "https://deno.land/x/drash@v2.8.0/mod.ts".`

## Expected Behavior

- https://github.com/drashland/drash/releases/tag/v2.8.0 using this

## Additional Context

```sh
deno --version
deno 1.32.5 (release, x86_64-pc-windows-msvc)
v8 11.2.214.9
typescript 5.0.3

```

**Comment by crookse** [comment]
Hey @sysmat, we know about this issue. It's related to https://github.com/denoland/dotland/issues/2696. We haven't pushed a new version yet because we're monitoring that Deno issue. As a workaround, you could do the following (also, sorry for the inconvenience!)

if you're still interested, another option is to import using a CDN

```ts
import * as Drash from "https://cdn.jsdelivr.net/gh/drashland/drash@v2.8.0/mod.ts";
```

**Comment by crookse** [comment]
Hey @sysmat, try pulling down v2.8.1. It's posted to deno's registry. Going to close this. Feel free to reopen if you experience issues.
